jwt:
  secretKey: C*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeShVmYq3s6v9y$B&E)H@McQfTjWnZr4u7w
  expiration: 200
  tokenHeader: Authorization
  tokenHead: Bearer

spring:
  application:
    name: teaching
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wzb199808.
    url: jdbc:mysql://118.31.16.137/teaching?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    hikari:
      validation-timeout: 3000
#      连接超时时间
      connection-timeout: 60000
#     idle超时时间
      idle-timeout: 600000
#     一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired）
      max-lifetime: 60000
#      数据库连接池大小
      maximum-pool-size: 10
#      控制连接池空闲连接的最小数量
      minimum-idle: 10
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 118.31.16.137
    port: 6379
    password: Wzb199808.
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
#kafka
  kafka:
    bootstrap-servers: 118.31.16.137:9092
    consumer:
      group-id: test-consumer-group
      #如果为true，则消费者的偏移量将在后台定期提交，默认值为true
      enable-auto-commit: true
      #如果'enable.auto.commit'为true，则消费者偏移自动提交给Kafka的频率（以毫秒为单位），默认值为5000。
      auto-commit-interval: 3000
    listener:
      missing-topics-fatal: false
server:
  servlet:
    context-path: /teaching
  port: 8080
mybatis:
  mapper-locations:
   - classpath:mappers/com/gdou/teaching/mbg/mapper/*.xml
   - classpath:mappers/com/gdou/teaching/dao/*.xml

logging:
  config: classpath:logback-dev.xml
# 配置文件服务类型
fileServer:
  type: oss
  uploadPath: /Users/bo/upload/


#caffeine缓存的参数
caffeine:
  course:
    #热点数据的最大数量
    maxSize: 15
    #淘汰时间
    expire-seconds: 180
  experiment:
    maxSize: 15
    expire-seconds: 180

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}

# aliyun oss
aliyun.oss.endpoint: "http://oss-cn-shenzhen.aliyuncs.com"
aliyun.oss.keyid: "LTAI4Fs1Ty9PLMeHW4WKjcm8"
aliyun.oss.keysecret: "BLXbfGH6j6ob5RnKMLY72q0UftC7qL"
aliyun.oss.bucketname: "20200514"

# aliyun filehost based on dev/test/prod(tha/idn)
aliyun.oss.filehost: dev

